name: SiftCore
version: '${project.version}'
main: net.siftvanilla.siftcore.SiftCorePlugin
bootstrapper: net.siftvanilla.siftcore.SiftCoreBootstrap
api-version: '26.2'
folia-supported: true
description: The gameplay core of SiftVanilla.
authors: [SiftVanilla]
website: https://github.com/faboit1/smpcore
dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
    Vault:
      load: BEFORE
      required: false
      join-classpath: true
    floodgate:
      load: BEFORE
      required: false
      join-classpath: true
