package net.siftvanilla.siftcore.feature.sell;

import io.papermc.paper.datacomponent.DataComponentTypes;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicReference;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.kyori.adventure.text.Component;
import net.siftvanilla.siftcore.core.Feature;
import net.siftvanilla.siftcore.core.Services;
import net.siftvanilla.siftcore.core.command.SiftCommand;
import net.siftvanilla.siftcore.core.config.ConfigProblem;
import net.siftvanilla.siftcore.core.config.Setting;
import net.siftvanilla.siftcore.core.permission.Permissions;
import net.siftvanilla.siftcore.core.selftest.SelfTest;
import net.siftvanilla.siftcore.ui.hub.HubEntry;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.inventory.ItemStack;
import org.bukkit.permissions.PermissionDefault;
import org.bukkit.persistence.PersistentDataType;

/**
 * The worth table and selling to the server. The table is generated at startup from configured base prices and the
 * server's own recipes (and regenerated by {@code /sift reload}); {@code /sell} opens a sell menu, {@code /sell hand}
 * and {@code /sell all} sell straight from the inventory, and {@code /worth} shows prices. The table and the rank
 * multipliers are offered to other features as {@link net.siftvanilla.siftcore.core.link.WorthLookup}.
 */
public final class SellFeature implements Feature, Listener {

    /** How often an online player's multiplier is re-read from their permissions (for the placeholder). */
    private static final long MULTIPLIER_REFRESH_TICKS = 20L * 60;

    private final Services services;
    private final Logger logger;
    private final Setting<SellSettings> settings;
    private final WorthService worth;
    private final SellService sales;
    private final SellMenus menus;
    private final SellCommands commands;
    private final int recipesSeen;
    private final int recipesSkipped;

    public SellFeature(Services services, List<ConfigProblem> problems) {
        this.services = services;
        this.logger = services.plugin().getLogger();
        ServerItems.Snapshot snapshot = ServerItems.snapshot();
        ItemCatalog catalog = snapshot.catalog();
        this.recipesSeen = snapshot.recipes();
        this.recipesSkipped = snapshot.skippedRecipes();
        AtomicReference<SellSettings> latest = new AtomicReference<>();
        this.settings = services.configs().register("features/sell.yml", reader -> {
            SellSettings parsed = SellSettings.parse(reader, catalog, services.core().get().money());
            latest.set(parsed);
            return parsed;
        }, problems);
        this.worth = new WorthService(this.settings, latest, services.scheduler()::owns);
        services.lang().register(SellMessages.class);
        Permissions perms = services.permissions();
        perms.declare(SellCommands.SELL, "Open the sell menu with /sell", true);
        perms.declare(SellCommands.SELL_HAND, "Sell the item in your hand with /sell hand", true);
        perms.declare(SellCommands.SELL_ALL, "Sell your whole inventory with /sell all", true);
        perms.declare(SellCommands.WORTH, "See what items sell for with /worth", true);
        perms.declare(SellCommands.WORTH_DETAILS, "See where a /worth price comes from", false);
        for (Map.Entry<String, Double> tier : this.settings.get().multipliers().entrySet()) {
            perms.declare(Multipliers.node(tier.getKey()), "Sell for " + Multipliers.format(tier.getValue())
                + " times the worth (the highest granted tier wins)", PermissionDefault.FALSE);
        }
        ItemHandout handout = new ItemHandout(services.deliveries(), this.logger);
        this.sales = new SellService(services, this.worth, this.settings, handout);
        this.menus = new SellMenus(services, this.worth, this.sales, handout);
        this.commands = new SellCommands(services, this.worth, this.sales, this.menus);
    }

    @Override
    public String id() {
        return "sell";
    }

    /** The worth table and rank multipliers, for other features ({@code WorthLookup}) and the shop. */
    public WorthService worth() {
        return this.worth;
    }

    @Override
    public void enable() {
        Bukkit.getPluginManager().registerEvents(this, this.services.plugin());
        Bukkit.getPluginManager().registerEvents(this.menus, this.services.plugin());
        this.services.hub().register(new HubEntry("sell", 25, SellMessages.HUB_LABEL, SellMessages.HUB_DESCRIPTION,
            SellCommands.SELL, this.menus::open));
        this.services.placeholders().register("sell_multiplier", "Your sell multiplier, like 1.5 (1 without a rank bonus)",
            player -> Multipliers.format(this.worth.cachedMultiplier(player.getUniqueId())));
        published(this.settings.get());
        this.settings.onReload(this::published);
        for (Player online : Bukkit.getOnlinePlayers()) {
            this.services.scheduler().entity(online, () -> track(online), null);
        }
    }

    /** Logs the table and writes the generated file (at startup and after every successful reload). */
    private void published(SellSettings settings) {
        WorthTable table = settings.table();
        this.logger.info("Worth table: " + table.size() + " sellable items (" + table.count(WorthTable.Origin.BASE) + " base, "
            + table.count(WorthTable.Origin.DERIVED) + " from recipes, " + table.count(WorthTable.Origin.OVERRIDE)
            + " overrides), using " + settings.recipes().size() + " of " + this.recipesSeen + " recipes ("
            + this.recipesSkipped + " special recipes skipped).");
        String text = WorthFile.render(settings, Instant.now());
        Path file = this.services.plugin().getDataFolder().toPath().resolve(WorthFile.NAME);
        this.services.scheduler().async(() -> {
            try {
                WorthFile.write(file, text);
            } catch (IOException e) {
                this.logger.log(Level.WARNING, "Could not write " + WorthFile.NAME, e);
            }
        });
    }

    @EventHandler(priority = EventPriority.MONITOR)
    public void onJoin(PlayerJoinEvent event) {
        track(event.getPlayer());
    }

    /** Reads the player's multiplier now and every minute while they are online (on their thread). */
    private void track(Player player) {
        this.worth.refresh(player);
        this.services.scheduler().entityTimer(player, () -> this.worth.refresh(player), null,
            MULTIPLIER_REFRESH_TICKS, MULTIPLIER_REFRESH_TICKS);
    }

    @Override
    public List<SiftCommand> commands() {
        return this.commands.all();
    }

    @Override
    public void disable() {
        this.menus.returnAll();
    }

    @Override
    public void selfTest(SelfTest test) {
        test.check(id(), "worth table", this::checkTable);
        test.check(id(), "only plain items sell", this::checkPlainItems);
        test.check(id(), "sale math", () -> {
            long total = SalePlan.of(List.of(new SalePlan.Line("minecraft:diamond", 64, 400))).total(1.5);
            return total == 38_400 ? null : "64 x $400 at 1.5x should pay $38,400, got " + total;
        });
        test.check(id(), "generated worth file", () -> {
            Path file = this.services.plugin().getDataFolder().toPath().resolve(WorthFile.NAME);
            try {
                return Files.size(file) > 0 ? null : WorthFile.NAME + " is empty";
            } catch (IOException e) {
                return WorthFile.NAME + " can't be read: " + e.getMessage();
            }
        });
    }

    /** Every base price is in the table unchanged and every price is a whole amount within the money limit. */
    private String checkTable() {
        SellSettings s = this.settings.get();
        WorthTable table = s.table();
        if (!s.tableProblems().isEmpty()) {
            return String.join("; ", s.tableProblems());
        }
        if (table.size() == 0) {
            return "the worth table is empty";
        }
        for (Map.Entry<String, Long> base : table.base().entrySet()) {
            String item = base.getKey();
            if (table.unsellable().contains(item)) {
                continue;
            }
            WorthTable.Entry entry = table.entry(item);
            if (entry == null) {
                return item + " has a base price but is missing from the table";
            }
            if (entry.origin() == WorthTable.Origin.BASE && entry.price() != base.getValue()) {
                return item + " has base price " + base.getValue() + " but the table says " + entry.price();
            }
        }
        long max = this.services.core().get().money().maxAmount();
        for (Map.Entry<String, WorthTable.Entry> entry : table.entries().entrySet()) {
            long price = entry.getValue().price();
            if (price < 1 || price > max) {
                return entry.getKey() + " has the price " + price + ", outside 1.." + max;
            }
            if (entry.getValue().origin() == WorthTable.Origin.DERIVED && entry.getValue().recipe() == null) {
                return entry.getKey() + " is derived but names no recipe";
            }
        }
        return null;
    }

    /** A plain stack sells; renamed, custom-data and damaged copies of it don't. */
    private String checkPlainItems() {
        Material plain = null;
        Material damageable = null;
        for (String key : this.worth.table().entries().keySet()) {
            Material material = Material.matchMaterial(key);
            if (material == null || !material.isItem()) {
                continue;
            }
            if (plain == null && material.getMaxStackSize() > 1) {
                plain = material;
            }
            if (damageable == null && material.getMaxDurability() > 0) {
                damageable = material;
            }
        }
        if (plain == null) {
            return "no stackable item is sellable";
        }
        ItemStack stack = ItemStack.of(plain, 3);
        if (this.worth.unitPrice(stack) <= 0) {
            return "a plain " + plain.getKey() + " does not sell";
        }
        ItemStack renamed = stack.clone();
        renamed.setData(DataComponentTypes.CUSTOM_NAME, Component.text("Renamed"));
        if (this.worth.unitPrice(renamed) != 0) {
            return "a renamed " + plain.getKey() + " sells";
        }
        ItemStack tagged = stack.clone();
        tagged.editPersistentDataContainer(pdc -> pdc.set(new NamespacedKey(this.services.plugin(), "selftest"),
            PersistentDataType.BYTE, (byte) 1));
        if (this.worth.unitPrice(tagged) != 0) {
            return "a " + plain.getKey() + " with custom data sells";
        }
        if (damageable != null) {
            ItemStack damaged = ItemStack.of(damageable);
            damaged.setData(DataComponentTypes.DAMAGE, 1);
            if (this.worth.unitPrice(damaged) != 0) {
                return "a damaged " + damageable.getKey() + " sells";
            }
        }
        return null;
    }
}
