package net.siftvanilla.siftcore.feature.sell;

import io.papermc.paper.datacomponent.DataComponentTypes;
import java.io.IOException;
import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.OptionalLong;
import java.util.UUID;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.Supplier;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.kyori.adventure.text.Component;
import net.siftvanilla.siftcore.core.Feature;
import net.siftvanilla.siftcore.core.Services;
import net.siftvanilla.siftcore.core.command.SiftCommand;
import net.siftvanilla.siftcore.core.config.ConfigProblem;
import net.siftvanilla.siftcore.core.config.Setting;
import net.siftvanilla.siftcore.core.item.ContainerItems;
import net.siftvanilla.siftcore.core.link.OrderMarket;
import net.siftvanilla.siftcore.core.permission.Permissions;
import net.siftvanilla.siftcore.core.placeholder.Placeholders;
import net.siftvanilla.siftcore.core.player.SettingCategories;
import net.siftvanilla.siftcore.core.player.SettingOptions;
import net.siftvanilla.siftcore.core.player.SharedSettings;
import net.siftvanilla.siftcore.core.selftest.SelfTest;
import net.siftvanilla.siftcore.core.teleport.CombatStatus;
import net.siftvanilla.siftcore.ui.hub.HubEntry;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.player.AsyncPlayerPreLoginEvent;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.event.player.PlayerQuitEvent;
import org.bukkit.inventory.ItemStack;
import org.bukkit.permissions.PermissionDefault;
import org.bukkit.persistence.PersistentDataType;

/**
 * The worth table and selling to the server. The table is generated at startup from configured base prices and the
 * server's own recipes (and regenerated by {@code /sift reload}); {@code /sell} opens a sell menu, {@code /sell hand},
 * {@code /sell hand all} and {@code /sell all} sell straight from the inventory (shulker box contents included),
 * {@code /sell mastery} shows the category levels that raise the multiplier, {@code /sell top} the best sellers and
 * {@code /worth} prices and the price list. The table and the rank multipliers are offered to other features as
 * {@link net.siftvanilla.siftcore.core.link.WorthLookup}; buy orders take part in sales through
 * {@link OrderMarket}; items from villager trades are marked so they can never be sold ({@link TradeGuard}).
 */
public final class SellFeature implements Feature, Listener {

    /** How often an online player's multiplier is re-read from their permissions (for the placeholder). */
    private static final long MULTIPLIER_REFRESH_TICKS = 20L * 60;
    /** How often the top sellers timer checks whether a refresh is due. */
    private static final Duration TOP_CHECK = Duration.ofSeconds(30);
    /** How long a login may wait for the player's mastery totals before it goes on and they load in the background. */
    private static final long LOGIN_LOAD_SECONDS = 5;

    private final Services services;
    private final Logger logger;
    private final Setting<SellSettings> settings;
    private final MasteryBook mastery;
    private final WorthService worth;
    private final OrderBids bids;
    private final SellService sales;
    private final SellMenus menus;
    private final SellDialogs dialogs;
    private final TopSellers top;
    private final SellHistory history;
    private final TradeGuard trades;
    private final SellCommands commands;
    private final AtomicReference<ShopOffers> shop = new AtomicReference<>(ShopOffers.NONE);
    private final SellLink link;
    private final int recipesSeen;
    private final int recipesSkipped;

    /**
     * @param combat what keeps combat-tagged players from selling
     * @param orders the buy-order market, read whenever a sale is worked out ({@link OrderMarket#NONE} without
     *               the orders feature)
     */
    public SellFeature(Services services, List<ConfigProblem> problems, CombatStatus combat, Supplier<OrderMarket> orders) {
        this.services = services;
        this.logger = services.plugin().getLogger();
        ServerItems.Snapshot snapshot = ServerItems.snapshot();
        ItemCatalog catalog = snapshot.catalog();
        this.recipesSeen = snapshot.recipes();
        this.recipesSkipped = snapshot.skippedRecipes();
        AtomicReference<SellSettings> latest = new AtomicReference<>();
        this.settings = services.configs().register("features/sell.yml", reader -> {
            SellSettings parsed = SellSettings.parse(reader, catalog, services.core().get().money());
            latest.set(parsed);
            return parsed;
        }, problems);
        this.mastery = new MasteryBook(services.database(), this.logger);
        this.worth = new WorthService(this.settings, latest, services.scheduler()::owns, this.mastery);
        services.lang().register(SellMessages.class);
        Permissions perms = services.permissions();
        perms.declare(SellCommands.SELL, "Open the sell menu with /sell, and /sell mastery, /sell top and /sell history", true);
        perms.declare(SellCommands.SELL_HAND, "Sell the item in your hand with /sell hand, and all of its kind with /sell hand all", true);
        perms.declare(SellCommands.SELL_ALL, "Sell your whole inventory with /sell all", true);
        perms.declare(SellCommands.WORTH, "See what items sell for with /worth and the price list", true);
        perms.declare(SellCommands.WORTH_DETAILS, "See where a /worth price comes from", false);
        perms.declare(SellCommands.ADMIN, "Look at and change players' sell mastery with /sell admin", false);
        for (Map.Entry<String, Double> tier : this.settings.get().multipliers().entrySet()) {
            perms.declare(Multipliers.node(tier.getKey()), "Sell for " + Multipliers.format(tier.getValue())
                + " times the worth (the highest granted tier wins)", PermissionDefault.FALSE);
        }
        services.settings().register(SellService.CONFIRM);
        // Sale receipts are a shared setting (spawner storage sales follow it too); selling acts on it.
        services.settings().reads(SharedSettings.SELL_RECEIPTS);
        ItemHandout handout = new ItemHandout(services.deliveries(), this.logger);
        this.bids = new OrderBids(orders);
        // "Sell to buy orders first" is offered only while there are buy orders (the orders feature may be off, and it
        // starts after this one): registered now, so the server's overrides can always name it.
        services.settings().register(SettingCategories.GENERAL, SellService.ORDERS, SettingOptions.<Boolean>builder()
            .availableWhen(() -> this.bids.market().available()).build());
        SaleBuilder builder = new SaleBuilder(this.worth, this.bids);
        this.sales = new SellService(services, this.worth, this.settings, handout, builder, this.bids, this.mastery, combat);
        this.menus = new SellMenus(services, this.worth, this.settings, this.sales, handout);
        this.top = new TopSellers(services.database(), services.directory()::name);
        this.history = new SellHistory(services);
        this.dialogs = new SellDialogs(services, this.worth, this.settings, this.sales, this.bids, this.mastery, this.top,
            this.shop::get);
        this.dialogs.browser(this::openBrowser);
        this.sales.chooseItems(this.menus::openFilled);
        this.menus.onMastery(this.dialogs::mastery);
        this.trades = new TradeGuard(() -> this.settings.get().markTrades(), services.scheduler()::owns);
        this.commands = new SellCommands(services, this.worth, this.settings, this.sales, this.menus, this.dialogs,
            this.history, this.mastery, this.bids, this.shop::get, this::openBrowser);
        this.link = new Link();
    }

    @Override
    public String id() {
        return "sell";
    }

    /** The worth table and rank multipliers, for other features ({@code WorthLookup}) and the shop. */
    public WorthService worth() {
        return this.worth;
    }

    /** Selling as the shop sees it (sell-back prices, carried counts, selling from a shop page). */
    public SellLink link() {
        return this.link;
    }

    /** Connects the shop, so prices, details and {@code /worth} can show and open it. */
    public void shop(ShopOffers offers) {
        this.shop.set(offers == null ? ShopOffers.NONE : offers);
    }

    private void openBrowser(Player player, String category, String query) {
        openBrowser(player, category, query, null);
    }

    private void openBrowser(Player player, String category, String query, Runnable back) {
        WorthBrowser.open(this.services, player, this.worth, this.settings, this.sales, this.bids, this.shop::get,
            this.dialogs, category, query, back);
    }

    @Override
    public void enable() {
        Bukkit.getPluginManager().registerEvents(this, this.services.plugin());
        Bukkit.getPluginManager().registerEvents(this.menus, this.services.plugin());
        Bukkit.getPluginManager().registerEvents(this.trades, this.services.plugin());
        this.services.hub().register(new HubEntry("sell", 25, SellMessages.HUB_LABEL, SellMessages.HUB_DESCRIPTION,
            SellCommands.SELL, this.menus::open));
        this.services.hub().register(new HubEntry("prices", 26, SellMessages.HUB_PRICES_LABEL,
            SellMessages.HUB_PRICES_DESCRIPTION, SellCommands.WORTH, player -> openBrowser(player, null, null)));
        placeholders();
        published(this.settings.get());
        this.settings.onReload(this::published);
        for (Player online : Bukkit.getOnlinePlayers()) {
            this.mastery.load(online.getUniqueId());
            this.services.scheduler().entity(online, () -> track(online), null);
        }
        this.services.scheduler().asyncTimer(this::refreshTop, Duration.ZERO, TOP_CHECK);
    }

    /** Reads the top sellers again once the configured interval has passed since the last read. */
    private void refreshTop() {
        long age = System.currentTimeMillis() - this.top.snapshot().at();
        if (age < this.settings.get().topRefresh().toMillis() && this.top.snapshot().at() > 0) {
            return;
        }
        this.top.refresh().whenComplete((snapshot, error) -> {
            if (error != null) {
                this.logger.log(Level.WARNING, "Could not read the top sellers", error);
            }
        });
    }

    private void placeholders() {
        Placeholders placeholders = this.services.placeholders();
        placeholders.register("sell_multiplier", "Your sell multiplier from sell.yml multipliers (1 when none apply; mastery not included)",
            player -> Multipliers.format(this.worth.cachedMultiplier(player.getUniqueId())));
        placeholders.registerPrefix("sell_multiplier_", "sell_multiplier_<category>",
            "Your multiplier for a sell category, rank plus mastery, like 1.6", (player, category) -> {
                if (this.worth.categories().category(category) == null) {
                    return "";
                }
                return Multipliers.format(this.worth.cachedRates(player.getUniqueId()).multiplier(category).doubleValue());
            });
        placeholders.registerPrefix("sell_mastery_", "sell_mastery_<category>", "Your sell mastery level in a category (0-5)",
            (player, category) -> {
                if (this.worth.categories().category(category) == null) {
                    return "";
                }
                return Integer.toString(this.worth.cachedRates(player.getUniqueId()).level(category));
            });
        placeholders.register("sell_sold", "Everything you sold to the server, at base value (what mastery counts)",
            player -> this.services.money().get().format(sold(player.getUniqueId())));
        placeholders.registerPrefix("worth_", "worth_<item>", "What one plain item sells for, like worth_diamond (empty when it can't be sold)",
            (player, item) -> {
                String key = ItemKeys.normalize(item);
                long price = key == null ? 0 : this.worth.table().price(key);
                return price <= 0 ? "" : this.services.money().get().format(price);
            });
        placeholders.registerPrefix("sell_top_name_", "sell_top_name_<n>", "Name of the n-th best seller (1-10)",
            (player, place) -> topPlace(place).map(TopSellers.Entry::name).orElse(""));
        placeholders.registerPrefix("sell_top_value_", "sell_top_value_<n>", "What the n-th best seller sold, formatted (1-10)",
            (player, place) -> topPlace(place).map(entry -> this.services.money().get().format(entry.sold())).orElse(""));
    }

    private Optional<TopSellers.Entry> topPlace(String place) {
        try {
            return this.top.snapshot().place(Integer.parseInt(place));
        } catch (NumberFormatException e) {
            return Optional.empty();
        }
    }

    /** What a player sold in total: live for online players, the last top-sellers read otherwise. */
    private long sold(UUID player) {
        return Math.max(this.mastery.total(player), this.top.snapshot().byUuid().getOrDefault(player, 0L));
    }

    /** Logs the table and writes the generated file (at startup and after every successful reload). */
    private void published(SellSettings settings) {
        WorthTable table = settings.table();
        this.logger.info("Worth table: " + table.size() + " sellable items (" + table.count(WorthTable.Origin.BASE) + " base, "
            + table.count(WorthTable.Origin.DERIVED) + " from recipes, " + table.count(WorthTable.Origin.OVERRIDE)
            + " overrides) in " + settings.categories().ids().size() + " categories, using " + settings.recipes().size()
            + " of " + this.recipesSeen + " recipes (" + this.recipesSkipped + " special recipes skipped). Best multiplier "
            + Multipliers.format(settings.highestMultiplier()) + "x (rank " + Multipliers.format(settings.highestRankMultiplier())
            + "x plus mastery " + Multipliers.format(settings.mastery().maxBonus().doubleValue()) + ").");
        String text = WorthFile.render(settings, Instant.now());
        Path file = this.services.plugin().getDataFolder().toPath().resolve(WorthFile.NAME);
        this.services.scheduler().async(() -> {
            try {
                WorthFile.write(file, text);
            } catch (IOException e) {
                this.logger.log(Level.WARNING, "Could not write " + WorthFile.NAME, e);
            }
        });
    }

    /**
     * Reads the player's mastery totals before they enter the world (the auth thread may wait), so their first sale
     * already counts from the right level.
     */
    @EventHandler(priority = EventPriority.MONITOR)
    public void onPreLogin(AsyncPlayerPreLoginEvent event) {
        if (event.getLoginResult() != AsyncPlayerPreLoginEvent.Result.ALLOWED) {
            return;
        }
        try {
            this.mastery.load(event.getUniqueId()).get(LOGIN_LOAD_SECONDS, TimeUnit.SECONDS);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        } catch (ExecutionException | TimeoutException e) {
            this.logger.log(Level.WARNING, "Reading the sell mastery of " + event.getName() + " at login took too long;"
                + " it finishes in the background", e);
        }
    }

    @EventHandler(priority = EventPriority.MONITOR)
    public void onJoin(PlayerJoinEvent event) {
        if (!this.mastery.present(event.getPlayer().getUniqueId())) {
            // Not read at login (it timed out, or a duplicate login's quit forgot it): read it now.
            this.mastery.load(event.getPlayer().getUniqueId());
        }
        track(event.getPlayer());
    }

    @EventHandler(priority = EventPriority.MONITOR)
    public void onQuit(PlayerQuitEvent event) {
        this.worth.forget(event.getPlayer().getUniqueId());
        this.mastery.forget(event.getPlayer().getUniqueId());
    }

    /** Reads the player's multiplier now and every minute while they are online (on their thread). */
    private void track(Player player) {
        this.worth.refresh(player);
        this.services.scheduler().entityTimer(player, () -> this.worth.refresh(player), null,
            MULTIPLIER_REFRESH_TICKS, MULTIPLIER_REFRESH_TICKS);
    }

    @Override
    public List<SiftCommand> commands() {
        return this.commands.all();
    }

    @Override
    public void disable() {
        this.menus.returnAll();
    }

    /** Selling as the shop sees it. */
    private final class Link implements SellLink {

        @Override
        public long sellBack(Player player, String itemKey) {
            return SellFeature.this.worth.unitPriceFor(player, itemKey);
        }

        @Override
        public long carried(Player player, String itemKey) {
            return SellFeature.this.sales.builder().carried(player, SellFeature.this.settings.get()).getOrDefault(itemKey, 0L);
        }

        @Override
        public boolean offerSell(Player player, String itemKey, Runnable back) {
            return SellFeature.this.sales.sellType(player, itemKey, true, back) == SellService.Outcome.ASKED;
        }
    }

    // ------------------------------------------------------------------ self-test

    @Override
    public void selfTest(SelfTest test) {
        test.check(id(), "worth table", this::checkTable);
        test.check(id(), "only plain items sell", this::checkPlainItems);
        test.check(id(), "sale math", () -> {
            long total = SalePlan.of(List.of(new SalePlan.Line("minecraft:diamond", 64, 400))).total(1.5);
            return total == 38_400 ? null : "64 x $400 at 1.5x should pay $38,400, got " + total;
        });
        test.check(id(), "generated worth file", () -> {
            Path file = this.services.plugin().getDataFolder().toPath().resolve(WorthFile.NAME);
            try {
                return Files.size(file) > 0 ? null : WorthFile.NAME + " is empty";
            } catch (IOException e) {
                return WorthFile.NAME + " can't be read: " + e.getMessage();
            }
        });
        test.check(id(), "no recipe gains", () -> {
            SellSettings s = this.settings.get();
            List<String> gains = WorthCalculator.gains(s);
            return gains.isEmpty() ? null : gains.getFirst() + (gains.size() > 1 ? " (+" + (gains.size() - 1) + " more)" : "");
        });
        test.check(id(), "sell categories cover the table", this::checkCategories);
        test.check(id(), "shop safe with mastery", this::checkShopWithMastery);
        test.check(id(), "shulker rebuild keeps other contents", this::checkShulkerRebuild);
        test.check(id(), "villager trades are marked", this::checkTradeMarker);
    }

    /** Every base price is in the table unchanged and every price is a whole amount within the money limit. */
    private String checkTable() {
        SellSettings s = this.settings.get();
        WorthTable table = s.table();
        if (!s.tableProblems().isEmpty()) {
            return String.join("; ", s.tableProblems());
        }
        if (table.size() == 0) {
            return "the worth table is empty";
        }
        for (Map.Entry<String, Long> base : table.base().entrySet()) {
            String item = base.getKey();
            if (table.unsellable().contains(item)) {
                continue;
            }
            WorthTable.Entry entry = table.entry(item);
            if (entry == null) {
                return item + " has a base price but is missing from the table";
            }
            if (entry.origin() == WorthTable.Origin.BASE && entry.price() != base.getValue()) {
                return item + " has base price " + base.getValue() + " but the table says " + entry.price();
            }
        }
        long max = this.services.core().get().money().maxAmount();
        for (Map.Entry<String, WorthTable.Entry> entry : table.entries().entrySet()) {
            long price = entry.getValue().price();
            if (price < 1 || price > max) {
                return entry.getKey() + " has the price " + price + ", outside 1.." + max;
            }
            if (entry.getValue().origin() == WorthTable.Origin.DERIVED && entry.getValue().recipe() == null) {
                return entry.getKey() + " is derived but names no recipe";
            }
        }
        return null;
    }

    /**
     * The shop is checked against the best multiplier anyone can reach (the best rank plus the top mastery bonus),
     * and no item the shop sells can be sold back for as much as it costs, even at that multiplier.
     */
    private String checkShopWithMastery() {
        SellSettings s = this.settings.get();
        BigDecimal highest = BigDecimal.valueOf(s.highestRankMultiplier()).add(s.mastery().maxBonus());
        if (BigDecimal.valueOf(s.highestMultiplier()).compareTo(highest) != 0) {
            return "the highest multiplier " + s.highestMultiplier() + " is not rank plus the top mastery bonus " + highest;
        }
        if (Math.abs(this.worth.current().highestMultiplier() - s.highestMultiplier()) > 1e-9) {
            return "the shop validates against " + this.worth.current().highestMultiplier() + " instead of " + s.highestMultiplier();
        }
        ShopOffers offers = this.shop.get();
        for (Map.Entry<String, WorthTable.Entry> entry : s.table().prices().entrySet()) {
            OptionalLong price = offers.price(entry.getKey());
            if (price.isEmpty()) {
                continue;
            }
            long best = SaleMath.withMultiplier(entry.getValue().price(), highest);
            if (best >= price.getAsLong()) {
                return entry.getKey() + " costs $" + price.getAsLong() + " in the shop but sells back for $" + best
                    + " at " + Multipliers.format(highest.doubleValue()) + "x";
            }
        }
        return null;
    }

    /** Every sellable item is in a category that exists; listed items are in the category that lists them. */
    private String checkCategories() {
        SellSettings s = this.settings.get();
        SellCategories categories = s.categories();
        for (Map.Entry<String, WorthTable.Entry> entry : s.table().entries().entrySet()) {
            String category = entry.getValue().category();
            if (categories.category(category) == null) {
                return entry.getKey() + " is in the category " + category + ", which does not exist";
            }
            String listed = categories.listed(entry.getKey());
            if (listed != null && !listed.equals(category)) {
                return entry.getKey() + " is listed in " + listed + " but the table puts it in " + category;
            }
        }
        String iron = s.table().category("minecraft:iron_block");
        if (iron != null && categories.category("mining") != null && !"mining".equals(iron)) {
            return "iron blocks should inherit mining from iron ingots, got " + iron;
        }
        return null;
    }

    /** Taking one kind out of a box leaves every other stack where it was, and an emptied box is plain again. */
    private String checkShulkerRebuild() {
        ItemStack box = ItemStack.of(Material.SHULKER_BOX);
        List<ItemStack> contents = new ArrayList<>();
        for (int i = 0; i < 27; i++) {
            contents.add(ItemStack.empty());
        }
        contents.set(3, ItemStack.of(Material.DIAMOND, 10));
        contents.set(7, ItemStack.of(Material.STICK, 5));
        contents.set(20, ItemStack.of(Material.DIAMOND, 64));
        ItemStack filled = ContainerItems.rebuild(box, contents);
        List<ItemStack> read = ContainerItems.contents(filled);
        if (read.size() < 21 || read.get(7).getType() != Material.STICK || read.get(20).getAmount() != 64) {
            return "a filled box does not keep positions: " + read;
        }
        ContainerItems.Extraction<ItemStack> taken = ContainerItems.extract(read, stack -> stack.getType() == Material.DIAMOND, 70);
        if (taken.units() != 70) {
            return "70 diamonds should come out, got " + taken.units();
        }
        List<ItemStack> after = ContainerItems.contents(ContainerItems.rebuild(filled, taken.remaining()));
        if (after.size() < 21 || after.get(7).getType() != Material.STICK || after.get(7).getAmount() != 5
            || after.get(20).getType() != Material.DIAMOND || after.get(20).getAmount() != 4 || !after.get(3).isEmpty()) {
            return "the rebuilt box moved or lost other stacks: " + after;
        }
        ContainerItems.Extraction<ItemStack> rest = ContainerItems.extract(after, stack -> true, Long.MAX_VALUE);
        ItemStack emptied = ContainerItems.rebuild(filled, rest.remaining());
        if (!emptied.isSimilar(box)) {
            return "an emptied plain box is not a plain box again";
        }
        if (ContainerItems.isShulker(box.asQuantity(2))) {
            return "a stacked box would be opened";
        }
        return null;
    }

    /** A marked item does not sell; marking keeps the item otherwise unchanged. */
    private String checkTradeMarker() {
        ItemStack emerald = ItemStack.of(Material.EMERALD, 3);
        ItemStack marked = TradeGuard.mark(emerald);
        if (!TradeGuard.marked(marked) || TradeGuard.marked(emerald)) {
            return "the trade marker is not applied to a copy";
        }
        if (this.worth.table().price("minecraft:emerald") > 0 && this.worth.unitPrice(marked) != 0) {
            return "a marked emerald sells";
        }
        if (marked.getType() != Material.EMERALD || marked.getAmount() != 3) {
            return "marking changed the item";
        }
        return null;
    }

    /** A plain stack sells; renamed, custom-data and damaged copies of it don't. */
    private String checkPlainItems() {
        Material plain = null;
        Material damageable = null;
        for (String key : this.worth.table().entries().keySet()) {
            Material material = Material.matchMaterial(key);
            if (material == null || !material.isItem()) {
                continue;
            }
            if (plain == null && material.getMaxStackSize() > 1) {
                plain = material;
            }
            if (damageable == null && material.getMaxDurability() > 0) {
                damageable = material;
            }
        }
        if (plain == null) {
            return "no stackable item is sellable";
        }
        ItemStack stack = ItemStack.of(plain, 3);
        if (this.worth.unitPrice(stack) <= 0) {
            return "a plain " + plain.getKey() + " does not sell";
        }
        ItemStack renamed = stack.clone();
        renamed.setData(DataComponentTypes.CUSTOM_NAME, Component.text("Renamed"));
        if (this.worth.unitPrice(renamed) != 0) {
            return "a renamed " + plain.getKey() + " sells";
        }
        ItemStack tagged = stack.clone();
        tagged.editPersistentDataContainer(pdc -> pdc.set(new NamespacedKey(this.services.plugin(), "selftest"),
            PersistentDataType.BYTE, (byte) 1));
        if (this.worth.unitPrice(tagged) != 0) {
            return "a " + plain.getKey() + " with custom data sells";
        }
        if (damageable != null) {
            ItemStack damaged = ItemStack.of(damageable);
            damaged.setData(DataComponentTypes.DAMAGE, 1);
            if (this.worth.unitPrice(damaged) != 0) {
                return "a damaged " + damageable.getKey() + " sells";
            }
        }
        return null;
    }
}
